site_name: AI Resume Analyzer

site_description: AI-powered Resume Analyzer using Python, Streamlit, and Gemini API

site_author: Mohit Ranjan

repo_url: https://github.com/ranjanmohit521/ai-resume-analyzer-gemini

nav:
- Home: index.md
- Features: features.md
- Installation: installation.md
- Usage: usage.md

markdown_extensions:
- toc:
permalink: true
separator: "_"
